### User register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName" : "Alu",
    "lastName" : "Karlapati",
    "email" : "Alu@gmail.com",
    "password" : "1228",
    "profileImageURL" : "abc.png"
}



### Author register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName" : "hari",
    "lastName" : "Karlapati",
    "email" : "hari1@gmail.com",
    "password" : "1234567890",
    "profileImageURL" : "xyz.jpg"
}



### User Login
POSt http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email" : "Alu@gmail.com",
    "password" : "1228"
}



### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email" : "hari1@gmail.com",
    "password" : "1234567890"
}


###AUTHOR OPERATIONS
###Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author" : "69ae8afbbae3ade836f814b0",
    "title" : "haru",
    "Category" : "lalli",
    "Content" : "applets"
}



###Read Articles of Authors
GET http://localhost:4000/author-api/articles/69ae8afbbae3ade836f814b0




###Edit the Articles
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author" : "6989679bbc9a0015fe5e19c1",
    "title" : "BAhu",
    "Category" : "Movie",
    "Content" : "Rana",
    "articleId" : "6989a932187167ffebc1b6b0"
}



###Soft Delete
PATCH http://localhost:4000/author-api/articles/69aec202bae3ade836f814fa/status
Content-Type: application/json

{
    "isArticleActive": true
}



###USER OPERATIONS
### Read all articles of User
GET http://localhost:4000/user-api/articles




### Add a comment
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "userId" : "698accf5021ed075f44f0032",
    "articleId" : "69aec202bae3ade836f814fa",
    "comment" : "Article is about Lalli and Haru"
}



###logout 
GET http://localhost:4000/common-api/logout




### Admin Auth
POST http://localhost:4000/common-api/login
Content-Type: application/json

    {
    "email" : "admin@gmail.com",
    "password" : "admin"
    }




###Invalid Path Req
GET http://localhost:4000/test




### New password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "newPassword" : "1228",
    "email" : "pushpa@gmail.com",
    "currentPassword" : "9989668210"
}


###ADMIN OPERATIONS
### Block User by Admin
PUT http://localhost:4000/admin-api/block
Content-Type: application/json

{
    "email" : "pushpa@gmail.com"
}



### Unblock User by Admin
PUT http://localhost:4000/admin-api/unblock
Content-Type: application/json

{
    "email" : "pushpa@gmail.com"
}